# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # DigiBankPO
  # ---------------------------------------------------------------------------
  - Name: DigiBankPO
    Domain: digi-bank-po.com
    Template:
      Count: 2
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # DigiBankSP
  # ---------------------------------------------------------------------------
  - Name: DigiBankSP
    Domain: digi-bank-sp.com
    Template:
      Count: 2
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # MagnetoCorpPO
  # ---------------------------------------------------------------------------
  - Name: MagnetoCorpPO
    Domain: magneto-corp-po.com
    Template:
      Count: 2
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # MagnetoCorpSP
  # ---------------------------------------------------------------------------
  - Name: MagnetoCorpSP
    Domain: magneto-corp-sp.com
    Template:
      Count: 2
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # HedgematicPO
  # ---------------------------------------------------------------------------
  - Name: HedgematicPO
    Domain: hedgematic-po.com
    Template:
      Count: 2
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # HedgematicSP
  # ---------------------------------------------------------------------------
  - Name: HedgematicSP
    Domain: hedgematic-sp.com
    Template:
      Count: 2
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # EcoBankSP
  # ---------------------------------------------------------------------------
  - Name: EcoBankSP
    Domain: eco-bank-sp.com
    Template:
      Count: 2
    Users:
      Count: 1
