language: java
jdk:
- openjdk8

services:
  - docker

env:
  - NODE_VERSION="--lts"

before_install:
  - nvm install $NODE_VERSION
  - sudo apt-get update
  - sudo apt-get install -y expect

script: ./tests/e2e/run_tests.sh

branches:
  only:
  - master
  - generalization
