#!/usr/local/bin/expect -f

set BASEDIR [file dirname $argv0]

send [cd $BASEDIR/../../cli/po-cli]

set timeout 120
spawn npm start
match_max 100000

expect {
    "*What is your username?*"                                  { send -- "2\r" }
    timeout                                                     { puts "\rtimed out"; exit 1 }
}

expect {
    "*Which action do you want to do?*"                         { send -- "3\r" }
    timeout                                                     { puts "\rtimed out"; exit 1 }
}

expect {
    "*What would you like to do?*"                              { send -- "1\r" }
    timeout                                                     { puts "\rtimed out"; exit 1 }
}

expect {
    "*Which purchase order do you want to manage?*PO0*"         { send -- "1\r" }
    timeout                                                     { puts "\rtimed out"; exit 1 }
}

expect {
    "*What do you want to do?*"                                 { send -- "1\r" }
    timeout                                                     { puts "\rtimed out"; exit 1 }
}

expect {
    "*Purchase Order approved*"                                 { }
    timeout                                                     { puts "\rtimed out"; exit 1 }
}

expect {
    "*Which action do you want to do?*"                         { send -- "4\r" }
    timeout                                                     { puts "\rtimed out"; exit 1 }
}
