version: '2'

services:
  orderer.example.com:
    extends:
        file: docker-compose-base.yaml
        service: orderer
    container_name: orderer.example.com

  tlsca.digi-bank-po.com:
    extends:
        file: docker-compose-base.yaml
        service: ca
    container_name: tlsca.digi-bank-po.com
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-digi-bank-po
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.digi-bank-po.com-cert.pem
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tlsca/tlsca.digi-bank-po.com-cert.pem
    volumes:
      - ../crypto-material/crypto-config/peerOrganizations/digi-bank-po.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../crypto-material/crypto-config/peerOrganizations/digi-bank-po.com/tlsca:/etc/hyperledger/fabric-ca-server-tlsca
    ports:
      - "7054:7054"

  peer0.digi-bank-po.com:
    extends:
        file: docker-compose-base.yaml
        service: peer
    container_name: peer0.digi-bank-po.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.digi-bank-po.com
      - CORE_PEER_ADDRESS=peer0.digi-bank-po.com:7051
      - CORE_PEER_LISTENADDRESS=peer0.digi-bank-po.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.digi-bank-po.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.digi-bank-po.com:7051
      - CORE_PEER_LOCALMSPID=DigiBankPOMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.digi-bank-po.com:5984

      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peerOrg1/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peerOrg1/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peerOrg1/tls/ca.crt
      - CORE_TLS_CLIENT_KEY_PATH=/etc/hyperledger/users/Admin@digi-bank-po.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/etc/hyperledger/users/Admin@digi-bank-po.com/tls/client.crt
    ports:
      - 7051:7051
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-material/crypto-config/peerOrganizations/digi-bank-po.com/peers/peer0.digi-bank-po.com/:/etc/hyperledger/peer
        - ../crypto-material/crypto-config/peerOrganizations/digi-bank-po.com/peers/peer0.digi-bank-po.com/:/etc/hyperledger/peerOrg1
        - ../crypto-material/crypto-config/peerOrganizations/digi-bank-sp.com/peers/peer0.digi-bank-sp.com/:/etc/hyperledger/peerOrg2
        - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-po.com/peers/peer0.magneto-corp-po.com/:/etc/hyperledger/peerOrg3
        - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-sp.com/peers/peer0.magneto-corp-sp.com/:/etc/hyperledger/peerOrg4
        - ../crypto-material/crypto-config/peerOrganizations/hedgematic-sp.com/peers/peer0.hedgematic-sp.com/:/etc/hyperledger/peerOrg5
        - ../crypto-material/crypto-config/peerOrganizations/eco-bank-sp.com/peers/peer0.eco-bank-sp.com/:/etc/hyperledger/peerOrg6
        - ../crypto-material/crypto-config/peerOrganizations/hedgematic-po.com/peers/peer0.hedgematic-po.com/:/etc/hyperledger/peerOrg7
        - ../crypto-material/crypto-config/peerOrganizations/digi-bank-po.com/users/:/etc/hyperledger/users
    depends_on:
      - orderer.example.com
      - couchdb.digi-bank-po.com

  couchdb.digi-bank-po.com:
    extends:
        file: docker-compose-base.yaml
        service: couchdb
    container_name: couchdb.digi-bank-po.com
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db

  digi-bank-po_cli:
    extends:
      file: docker-compose-base.yaml
      service: clibase
    container_name: digi-bank-po_cli
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.digi-bank-po.com:7051
      - CORE_PEER_LOCALMSPID=DigiBankPOMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/config/crypto-config/peerOrganizations/digi-bank-po.com/users/Admin@digi-bank-po.com/msp

      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peerOrg1/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peerOrg1/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peerOrg1/tls/ca.crt
      - CORE_TLS_CLIENT_KEY_PATH=/etc/hyperledger/users/Admin@digi-bank-po.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/etc/hyperledger/users/Admin@digi-bank-po.com/tls/client.crt
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-material/crypto-config/peerOrganizations/digi-bank-po.com/peers/peer0.digi-bank-po.com/:/etc/hyperledger/peerOrg1
      - ../crypto-material/crypto-config/peerOrganizations/digi-bank-sp.com/peers/peer0.digi-bank-sp.com/:/etc/hyperledger/peerOrg2
      - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-po.com/peers/peer0.magneto-corp-po.com/:/etc/hyperledger/peerOrg3
      - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-sp.com/peers/peer0.magneto-corp-sp.com/:/etc/hyperledger/peerOrg4
      - ../crypto-material/crypto-config/peerOrganizations/hedgematic-sp.com/peers/peer0.hedgematic-sp.com/:/etc/hyperledger/peerOrg5
      - ../crypto-material/crypto-config/peerOrganizations/eco-bank-sp.com/peers/peer0.eco-bank-sp.com/:/etc/hyperledger/peerOrg6
      - ../crypto-material/crypto-config/peerOrganizations/digi-bank-po.com/users/:/etc/hyperledger/users
    depends_on:
      - peer0.digi-bank-po.com

  tlsca.digi-bank-sp.com:
    extends:
        file: docker-compose-base.yaml
        service: ca
    container_name: tlsca.digi-bank-sp.com
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-digi-bank-sp
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.digi-bank-sp.com-cert.pem
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tlsca/tlsca.digi-bank-sp.com-cert.pem
    volumes:
      - ../crypto-material/crypto-config/peerOrganizations/digi-bank-sp.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../crypto-material/crypto-config/peerOrganizations/digi-bank-sp.com/tlsca:/etc/hyperledger/fabric-ca-server-tlsca
    ports:
      - "8054:7054"

  tlsca.magneto-corp-po.com:
    extends:
        file: docker-compose-base.yaml
        service: ca
    container_name: tlsca.magneto-corp-po.com
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-magneto-corp-po
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.magneto-corp-po.com-cert.pem
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tlsca/tlsca.magneto-corp-po.com-cert.pem
    volumes:
      - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-po.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-po.com/tlsca:/etc/hyperledger/fabric-ca-server-tlsca
    ports:
      - "9054:7054"

  peer0.magneto-corp-po.com:
    extends:
        file: docker-compose-base.yaml
        service: peer
    container_name: peer0.magneto-corp-po.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.magneto-corp-po.com
      - CORE_PEER_ADDRESS=peer0.magneto-corp-po.com:9051
      - CORE_PEER_LISTENADDRESS=peer0.magneto-corp-po.com:9051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.magneto-corp-po.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.magneto-corp-po.com:9051
      - CORE_PEER_LOCALMSPID=MagnetoCorpPOMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.magneto-corp-po.com:5984

      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peerOrg3/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peerOrg3/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peerOrg3/tls/ca.crt
      - CORE_TLS_CLIENT_KEY_PATH=/etc/hyperledger/users/Admin@magneto-corp-po.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/etc/hyperledger/users/Admin@magneto-corp-po.com/tls/client.crt
    ports:
      - 9051:9051
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-po.com/peers/peer0.magneto-corp-po.com/:/etc/hyperledger/peer
        - ../crypto-material/crypto-config/peerOrganizations/digi-bank-po.com/peers/peer0.digi-bank-po.com/:/etc/hyperledger/peerOrg1
        - ../crypto-material/crypto-config/peerOrganizations/digi-bank-sp.com/peers/peer0.digi-bank-sp.com/:/etc/hyperledger/peerOrg2
        - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-po.com/peers/peer0.magneto-corp-po.com/:/etc/hyperledger/peerOrg3
        - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-sp.com/peers/peer0.magneto-corp-sp.com/:/etc/hyperledger/peerOrg4
        - ../crypto-material/crypto-config/peerOrganizations/hedgematic-sp.com/peers/peer0.hedgematic-sp.com/:/etc/hyperledger/peerOrg5
        - ../crypto-material/crypto-config/peerOrganizations/eco-bank-sp.com/peers/peer0.eco-bank-sp.com/:/etc/hyperledger/peerOrg6
        - ../crypto-material/crypto-config/peerOrganizations/hedgematic-po.com/peers/peer0.hedgematic-po.com/:/etc/hyperledger/peerOrg7
        - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-po.com/users/:/etc/hyperledger/users
    depends_on:
      - orderer.example.com
      - couchdb.magneto-corp-po.com

  couchdb.magneto-corp-po.com:
    extends:
        file: docker-compose-base.yaml
        service: couchdb
    container_name: couchdb.magneto-corp-po.com
    ports:
      - 7984:5984
    environment:
      DB_URL: http://localhost:5984/member_db

  magneto-corp-po_cli:
    extends:
      file: docker-compose-base.yaml
      service: clibase
    container_name: magneto-corp-po_cli
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.magneto-corp-po.com:9051
      - CORE_PEER_LOCALMSPID=MagnetoCorpPOMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/config/crypto-config/peerOrganizations/magneto-corp-po.com/users/Admin@magneto-corp-po.com/msp

      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peerOrg3/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peerOrg3/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peerOrg3/tls/ca.crt
      - CORE_TLS_CLIENT_KEY_PATH=/etc/hyperledger/users/Admin@magneto-corp-po.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/etc/hyperledger/users/Admin@magneto-corp-po.com/tls/client.crt
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-material/crypto-config/peerOrganizations/digi-bank-po.com/peers/peer0.digi-bank-po.com/:/etc/hyperledger/peerOrg1
      - ../crypto-material/crypto-config/peerOrganizations/digi-bank-sp.com/peers/peer0.digi-bank-sp.com/:/etc/hyperledger/peerOrg2
      - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-po.com/peers/peer0.magneto-corp-po.com/:/etc/hyperledger/peerOrg3
      - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-sp.com/peers/peer0.magneto-corp-sp.com/:/etc/hyperledger/peerOrg4
      - ../crypto-material/crypto-config/peerOrganizations/hedgematic-sp.com/peers/peer0.hedgematic-sp.com/:/etc/hyperledger/peerOrg5
      - ../crypto-material/crypto-config/peerOrganizations/eco-bank-sp.com/peers/peer0.eco-bank-sp.com/:/etc/hyperledger/peerOrg6
      - ../crypto-material/crypto-config/peerOrganizations/hedgematic-po.com/peers/peer0.hedgematic-po.com/:/etc/hyperledger/peerOrg7
      - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-po.com/users/:/etc/hyperledger/users
    depends_on:
      - peer0.magneto-corp-po.com

  tlsca.hedgematic-po.com:
    extends:
        file: docker-compose-base.yaml
        service: ca
    container_name: tlsca.hedgematic-po.com
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-hedgematic-po
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hedgematic-po.com-cert.pem
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tlsca/tlsca.hedgematic-po.com-cert.pem
    volumes:
      - ../crypto-material/crypto-config/peerOrganizations/hedgematic-po.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../crypto-material/crypto-config/peerOrganizations/hedgematic-po.com/tlsca:/etc/hyperledger/fabric-ca-server-tlsca
    ports:
      - "11054:7054"

  peer0.hedgematic-po.com:
    extends:
        file: docker-compose-base.yaml
        service: peer
    container_name: peer0.hedgematic-po.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.hedgematic-po.com
      - CORE_PEER_ADDRESS=peer0.hedgematic-po.com:11051
      - CORE_PEER_LISTENADDRESS=peer0.hedgematic-po.com:11051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.hedgematic-po.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hedgematic-po.com:11051
      - CORE_PEER_LOCALMSPID=HedgematicPOMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.hedgematic-po.com:5984

      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peerOrg7/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peerOrg7/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peerOrg7/tls/ca.crt
      - CORE_TLS_CLIENT_KEY_PATH=/etc/hyperledger/users/Admin@hedgematic-po.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/etc/hyperledger/users/Admin@hedgematic-po.com/tls/client.crt
    ports:
      - 11051:11051
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-material/crypto-config/peerOrganizations/hedgematic-po.com/peers/peer0.hedgematic-po.com/:/etc/hyperledger/peer
        - ../crypto-material/crypto-config/peerOrganizations/digi-bank-po.com/peers/peer0.digi-bank-po.com/:/etc/hyperledger/peerOrg1
        - ../crypto-material/crypto-config/peerOrganizations/digi-bank-sp.com/peers/peer0.digi-bank-sp.com/:/etc/hyperledger/peerOrg2
        - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-po.com/peers/peer0.magneto-corp-po.com/:/etc/hyperledger/peerOrg3
        - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-sp.com/peers/peer0.magneto-corp-sp.com/:/etc/hyperledger/peerOrg4
        - ../crypto-material/crypto-config/peerOrganizations/eco-bank-sp.com/peers/peer0.eco-bank-sp.com/:/etc/hyperledger/peerOrg6
        - ../crypto-material/crypto-config/peerOrganizations/hedgematic-po.com/peers/peer0.hedgematic-po.com/:/etc/hyperledger/peerOrg7
        - ../crypto-material/crypto-config/peerOrganizations/hedgematic-po.com/users/:/etc/hyperledger/users
    depends_on:
      - orderer.example.com
      - couchdb.hedgematic-po.com

  couchdb.hedgematic-po.com:
    extends:
        file: docker-compose-base.yaml
        service: couchdb
    container_name: couchdb.hedgematic-po.com
    ports:
      - 9984:5984
    environment:
      DB_URL: http://localhost:9984/member_db

  hedgematic-po_cli:
    extends:
      file: docker-compose-base.yaml
      service: clibase
    container_name: hedgematic-po_cli
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.hedgematic-po.com:11051
      - CORE_PEER_LOCALMSPID=HedgematicPOMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/config/crypto-config/peerOrganizations/hedgematic-po.com/users/Admin@hedgematic-po.com/msp

      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peerOrg7/tls/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peerOrg7/tls/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peerOrg7/tls/ca.crt
      - CORE_TLS_CLIENT_KEY_PATH=/etc/hyperledger/users/Admin@hedgematic-po.com/tls/client.key
      - CORE_TLS_CLIENT_CERT_PATH=/etc/hyperledger/users/Admin@hedgematic-po.com/tls/client.crt
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-material/crypto-config/peerOrganizations/digi-bank-po.com/peers/peer0.digi-bank-po.com/:/etc/hyperledger/peerOrg1
      - ../crypto-material/crypto-config/peerOrganizations/digi-bank-sp.com/peers/peer0.digi-bank-sp.com/:/etc/hyperledger/peerOrg2
      - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-po.com/peers/peer0.magneto-corp-po.com/:/etc/hyperledger/peerOrg3
      - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-sp.com/peers/peer0.magneto-corp-sp.com/:/etc/hyperledger/peerOrg4
      - ../crypto-material/crypto-config/peerOrganizations/hedgematic-sp.com/peers/peer0.hedgematic-sp.com/:/etc/hyperledger/peerOrg5
      - ../crypto-material/crypto-config/peerOrganizations/eco-bank-sp.com/peers/peer0.eco-bank-sp.com/:/etc/hyperledger/peerOrg6
      - ../crypto-material/crypto-config/peerOrganizations/hedgematic-po.com/peers/peer0.hedgematic-po.com/:/etc/hyperledger/peerOrg7
      - ../crypto-material/crypto-config/peerOrganizations/hedgematic-po.com/users/:/etc/hyperledger/users
    depends_on:
      - peer0.hedgematic-po.com

  tlsca.magneto-corp-sp.com:
    extends:
        file: docker-compose-base.yaml
        service: ca
    container_name: tlsca.magneto-corp-sp.com
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-magneto-corp-sp
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.magneto-corp-sp.com-cert.pem
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tlsca/tlsca.magneto-corp-sp.com-cert.pem
    volumes:
      - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-sp.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../crypto-material/crypto-config/peerOrganizations/magneto-corp-sp.com/tlsca:/etc/hyperledger/fabric-ca-server-tlsca
    ports:
      - "10054:7054"

  tlsca.hedgematic-sp.com:
    extends:
        file: docker-compose-base.yaml
        service: ca
    container_name: tlsca.hedgematic-sp.com
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-hedgematic-sp
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hedgematic-sp.com-cert.pem
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tlsca/tlsca.hedgematic-sp.com-cert.pem
    volumes:
      - ../crypto-material/crypto-config/peerOrganizations/hedgematic-sp.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../crypto-material/crypto-config/peerOrganizations/hedgematic-sp.com/tlsca:/etc/hyperledger/fabric-ca-server-tlsca
    ports:
      - "12054:7054"

  tlsca.eco-bank-sp.com:
    extends:
        file: docker-compose-base.yaml
        service: ca
    container_name: tlsca.eco-bank-sp.com
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-eco-bank-sp
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.eco-bank-sp.com-cert.pem
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tlsca/tlsca.eco-bank-sp.com-cert.pem
    volumes:
      - ../crypto-material/crypto-config/peerOrganizations/eco-bank-sp.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../crypto-material/crypto-config/peerOrganizations/eco-bank-sp.com/tlsca:/etc/hyperledger/fabric-ca-server-tlsca
    ports:
      - "13054:7054"
