version: '2'

services:
  rest_server:
    environment:
      - WALLET_PATH=/etc/tradefinance/wallet
      - CONNECTION_PROFILE_PATH=/etc/tradefinance/connection_profile.json
      - FABRIC_IDENTITY=services
    volumes:
      - ../../network/crypto-material/crypto-config:/msp

  ep_rest_server:
    image: tradefinance/porest
    extends:
      service: rest_server
    environment:
      - PORT=6000

  sp_rest_server:
    image: tradefinance/sprest
    extends:
      service: rest_server
    environment:
      - PORT=7000
